version: "3.9" # dicker composeファイルのバージョンを指定 マイナーバージョン（3.9など）を指定するようにする
services:
  app:
    build: ./infra/php # dockerファイルがおいてあるディレクトリ
    volumes:
      - ./backend:/work # マウントするフォルダ

# 追記
  web:
      image: nginx:1.20-alpine
      ports:
        - 8080:80
      volumes:
        - ./backend:/work
        - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      working_dir: /work