version: "3.9" # dicker composeファイルのバージョンを指定 マイナーバージョン（3.9など）を指定するようにする
services:
  app:
    build: ./infra/php # dockerファイルがおいてあるディレクトリ
    volumes:
      - ./backend:/work # マウントするフォルダ

# 追記
  web:
      image: nginx:1.20-alpine
      ports:
        - 8080:80
      volumes:
        - ./backend:/work
        - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      working_dir: /work
  
  # 追記
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: # 名前付きボリュームというもの（docker側で管理しているディレクトリのようなもの）
  # dockerコンテナが消えてもデータを残したい場合はデータボリュームを作ってマウントさせている
  # 次回 docker-compose up をした時にこのボリューム内のデータを db-store:/var/lib/mysql にコピーする